services:
  postgres:
    image: postgres:17
    container_name: evo1-postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "55432:5432"   # host -> container
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: evo1-pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGPASSFILE: /var/lib/pgadmin/pgpass
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      # mount read-only, then copy to writable location in entrypoint
      - ./pgadmin/pgpass:/tmp/pgpass:ro
    entrypoint: >
      /bin/sh -c "
      cp /tmp/pgpass /var/lib/pgadmin/pgpass || true;
      chmod 600 /var/lib/pgadmin/pgpass || true;
      /entrypoint.sh
      "

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: evo1-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio_init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: evo1-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minio minio12345;
      mc mb -p local/lake || true;
      mc anonymous set download local/lake || true;
      echo 'MinIO bucket lake is ready.';
      "

  duckdb:
    image: duckdb/duckdb:latest
    container_name: evo1-duckdb
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio_init:
        condition: service_started
    volumes:
      - ./duckdb:/data
    tty: true
    stdin_open: true


volumes:
  pg_data:
  pgadmin_data:
  minio_data:
